{
"schemas": {
  "persons": {
    "$schema": "http://json-schema.org/draft-03/schema#",
    "id": "http://www.popoloproject.com/schemas/person.json#",
    "title": "Person",
    "description": "A real person, alive or dead",
    "type": "object",
    "rdfSubject": "id",
    "properties": {
      "id": {
        "description": "The person's unique identifier",
        "type": ["string", "null"],
        "rdfType": "id"
      },
      "name": {
        "description": "A person's preferred full name",
        "type": ["string", "null"]
      },
      "other_names": {
        "description": "Alternate or former names",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/other_name.json#"
        }
      },
      "identifiers": {
        "description": "Issued identifiers",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/identifier.json#"
        }
      },
      "family_name": {
        "description": "One or more family names",
        "type": ["string", "null"]
      },
      "given_name": {
        "description": "One or more primary given names",
        "type": ["string", "null"]
      },
      "additional_name": {
        "description": "One or more secondary given names",
        "type": ["string", "null"]
      },
      "honorific_prefix": {
        "description": "One or more honorifics preceding a person's name",
        "type": ["string", "null"]
      },
      "honorific_suffix": {
        "description": "One or more honorifics following a person's name",
        "type": ["string", "null"]
      },
      "patronymic_name": {
        "description": "One or more patronymic names",
        "type": ["string", "null"]
      },
      "sort_name": {
        "description": "A name to use in a lexicographically ordered list",
        "type": ["string", "null"]
      },
      "email": {
        "description": "A preferred email address",
        "type": ["string", "null"],
        "format": "email"
      },
      "gender": {
        "description": "A gender",
        "type": ["string", "null"]
      },
      "birth_date": {
        "description": "A date of birth",
        "type": ["string", "null"],
        "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
      },
      "death_date": {
        "description": "A date of death",
        "type": ["string", "null"],
        "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
      },
      "image": {
        "description": "A URL of a head shot",
        "type": ["string", "null"],
        "format": "uri"
      },
      "summary": {
        "description": "A one-line account of a person's life",
        "type": ["string", "null"]
      },
      "biography": {
        "description": "An extended account of a person's life",
        "type": ["string", "null"]
      },
      "national_identity": {
        "description": "A national identity",
        "type": ["string", "null"]
      },
      "contact_details": {
        "description": "Means of contacting the person",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/contact_detail.json#"
        }
      },
      "links": {
        "description": "URLs to documents about the person",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/link.json#"
        }
      },
      "memberships": {
        "description": "The person's memberships",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/membership.json#"
        }
      },
      "motions": {
        "description": "The person's motions",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/motion.json#"
        }
      },
      "speeches": {
        "description": "The person's speeches",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/speech.json#"
        }
      },
      "votes": {
        "description": "Votes cast by the person",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/vote.json#"
        }
      },
      "created_at": {
        "description": "The time at which the resource was created",
        "type": ["string", "null"],
        "format": "date-time"
      },
      "updated_at": {
        "description": "The time at which the resource was last modified",
        "type": ["string", "null"],
        "format": "date-time"
      },
      "sources": {
        "description": "URLs to documents from which the resource is derived",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/link.json#"
        }
      }
    }
  },
  "organizations": {
    "$schema": "http://json-schema.org/draft-03/schema#",
    "id": "http://www.popoloproject.com/schemas/organization.json#",
    "title": "Organization",
    "description": "A group with a common purpose or reason for existence that goes beyond the set of people belonging to it",
    "type": "object",
    "properties": {
      "id": {
        "description": "The organization's unique identifier",
        "type": ["string", "null"],
        "rdfType": "id"
      },
      "name": {
        "description": "A primary name, e.g. a legally recognized name",
        "type": ["string", "null"]
      },
      "other_names": {
        "description": "Alternate or former names",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/other_name.json#"
        }
      },
      "identifiers": {
        "description": "Issued identifiers",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/identifier.json#"
        }
      },
      "classification": {
        "description": "An organization category, e.g. committee",
        "type": ["string", "null"]
      },
      "parent_id": {
        "description": "The ID of the organization that contains this organization",
        "type": ["string", "null"]
      },
      "parent": {
        "description": "The organization that contains this organization",
        "$ref": "http://www.popoloproject.com/schemas/organization.json#"
      },
      "area_id": {
        "description": "The ID of the geographic area to which this organization is related",
        "type": ["string", "null"]
      },
      "area": {
        "description": "The geographic area to which this organization is related",
        "$ref": "http://www.popoloproject.com/schemas/area.json#"
      },
      "abstract": {
        "description": "A one-line description of an organization",
        "type": ["string", "null"]
      },
      "description": {
        "description": "An extended description of an organization",
        "type": ["string", "null"]
      },
      "founding_date": {
        "description": "A date of founding",
        "type": ["string", "null"],
        "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
      },
      "dissolution_date": {
        "description": "A date of dissolution",
        "type": ["string", "null"],
        "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
      },
      "image": {
        "description": "A URL of an image",
        "type": ["string", "null"],
        "format": "uri"
      },
      "contact_details": {
        "description": "Means of contacting the organization",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/contact_detail.json#"
        }
      },
      "links": {
        "description": "URLs to documents about the organization",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/link.json#"
        }
      },
      "memberships": {
        "description": "The memberships of the members of the organization and of the organization itself",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/membership.json#"
        }
      },
      "posts": {
        "description": "Posts within the organization",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/post.json#"
        }
      },
      "motions": {
        "description": "Motions within the organization",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/motion.json#"
        }
      },
      "vote_events": {
        "description": "Vote events in which members of the organization are voting",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/vote_event.json#"
        }
      },
      "votes": {
        "description": "Votes cast by the organization",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/vote.json#"
        }
      },
      "children": {
        "description": "The sub-organizations of the organization",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/organization.json#"
        }
      },
      "created_at": {
        "description": "The time at which the resource was created",
        "type": ["string", "null"],
        "format": "date-time"
      },
      "updated_at": {
        "description": "The time at which the resource was last modified",
        "type": ["string", "null"],
        "format": "date-time"
      },
      "sources": {
        "description": "URLs to documents from which the resource is derived",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/link.json#"
        }
      }
    }
  },
  "memberships": {
    "$schema": "http://json-schema.org/draft-03/schema#",
    "id": "http://www.popoloproject.com/schemas/membership.json#",
    "title": "Membership",
    "description": "A relationship between a member and an organization",
    "type": "object",
    "properties": {
      "id": {
        "description": "The membership's unique identifier",
        "type": ["string", "null"],
        "rdfType": "id"
      },
      "label": {
        "description": "A label describing the membership",
        "type": ["string", "null"]
      },
      "role": {
        "description": "The role that the member fulfills in the organization",
        "type": ["string", "null"]
      },
      "member": {
        "description": "The person or organization that is a member of the organization",
        "type": ["object", "null"]
      },
      "person_id": {
        "description": "The ID of the person who is a member of the organization",
        "type": ["string", "null"],
        "rdfName": "person",
        "rdfType": "id",
        "rdfReverseName": "memberships"
      },
      "person": {
        "description": "The person who is a member of the organization",
        "$ref": "http://www.popoloproject.com/schemas/person.json#",
        "rdfReverseName": "memberships"
      },
      "organization_id": {
        "description": "The ID of the organization in which the person or organization is a member",
        "type": ["string", "null"],
        "rdfName": "organization",
        "rdfType": "id",
        "rdfReverseName": "memberships"
      },
      "organization": {
        "description": "The organization in which the person or organization is a member",
        "$ref": "http://www.popoloproject.com/schemas/organization.json#",
        "rdfReverseName": "memberships"
      },
      "post_id": {
        "description": "The ID of the post held by the member in the organization through this membership",
        "type": ["string", "null"]
      },
      "post": {
        "description": "The post held by the member in the organization through this membership",
        "$ref": "http://www.popoloproject.com/schemas/post.json#"
      },
      "on_behalf_of_id": {
        "description": "The ID of the organization on whose behalf the person is a member of the organization",
        "type": ["string", "null"]
      },
      "on_behalf_of": {
        "description": "The organization on whose behalf the person is a member of the organization",
        "$ref": "http://www.popoloproject.com/schemas/organization.json#"
      },
      "area_id": {
        "description": "The ID of the geographic area to which this membership is related",
        "type": ["string", "null"]
      },
      "area": {
        "description": "The geographic area to which this membership is related",
        "$ref": "http://www.popoloproject.com/schemas/area.json#"
      },
      "start_date": {
        "description": "The date on which the relationship began",
        "type": ["string", "null"],
        "pattern": "^[0-9]{4}((-[0-9]{2}){0,2}|(-[0-9]{2}){2}(T[0-9]{2}(:[0-9]{2}(:[0-9]{2})?)?Z)?)$"
      },
      "end_date": {
        "description": "The date on which the relationship ended",
        "type": ["string", "null"],
        "pattern": "^[0-9]{4}((-[0-9]{2}){0,2}|(-[0-9]{2}){2}(T[0-9]{2}(:[0-9]{2}(:[0-9]{2})?)?Z)?)$"
      },
      "contact_details": {
        "description": "Means of contacting the member of the organization",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/contact_detail.json#"
        }
      },
      "links": {
        "description": "URLs to documents about the membership",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/link.json#"
        }
      },
      "created_at": {
        "description": "The time at which the resource was created",
        "type": ["string", "null"],
        "format": "date-time"
      },
      "updated_at": {
        "description": "The time at which the resource was last modified",
        "type": ["string", "null"],
        "format": "date-time"
      },
      "sources": {
        "description": "URLs to documents from which the resource is derived",
        "type": "array",
        "items": {
          "$ref": "http://www.popoloproject.com/schemas/link.json#"
        }
      }
    }
  }
}
}
